from cflow._error import UnpackingException as UnpackingException
from cflow._skippable import Skippable as Skippable, _Skippable, _ValueWith
from typing import Callable, Final, Literal, NoReturn, Protocol, TypeGuard, TypeVar

T = TypeVar('T')
S = TypeVar('S')
type _MapFunc[T, S] = Callable[[T], S]

class OptionProtocol[T](Protocol):
    def map[S](self, func: _MapFunc[T, S]) -> OptionProtocol[S]: ...
    def map_or[S](self, func: _MapFunc[T, S], default: S) -> OptionProtocol[S]: ...
    def is_some(self) -> bool: ...
    def is_nothing(self) -> bool: ...
    def unwrap(self) -> T: ...
    def get_some(self) -> _ValueWith[T]: ...

def is_some[T](obj: Option[T]) -> TypeGuard[Some[T]]: ...
def is_nothing[T](obj: Option[T]) -> TypeGuard[Nothing]: ...

class Some[T]:
    value: T
    __match_args__: tuple[Literal['value']]
    def __init__(self, value: T) -> None: ...
    def map[S](self, func: _MapFunc[T, S]) -> Some[S]: ...
    def map_or[S](self, func: _MapFunc[T, S], default: S) -> Some[S]: ...
    def is_some(self) -> Literal[True]: ...
    def is_nothing(self) -> Literal[False]: ...
    def unwrap(self) -> T: ...
    def get_some(self) -> _ValueWith[T]: ...

class Nothing:
    Skip: Final[_Skippable]
    slots: tuple[()]
    __match_args__: tuple[()]
    def map[T, S](self, func: _MapFunc[T, S]) -> Nothing: ...
    def map_or[T, S](self, func: _MapFunc[T, S], default: S) -> S: ...
    def is_some(self) -> Literal[False]: ...
    def is_nothing(self) -> Literal[True]: ...
    def unwrap(self) -> NoReturn: ...
    def get_some(self) -> _ValueWith[NoReturn]: ...
type Option[T] = Some[T] | Nothing
