import types
from _typeshed import Incomplete

class _Skip(Exception): ...

class _Skippable:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_tp, *_): ...

Skippable: Incomplete

class _ValueWith[T]:
    value: T
    def __init__(self, value: T) -> None: ...
    def __enter__(self) -> T: ...
    def __exit__(self, exception_type: type[BaseException] | None, exception_value: BaseException | None, exception_traceback: types.TracebackType | None) -> None: ...
